'use strict';

// The 216 item locations ("checks") of A Link to the Past, grouped by region.
// Names follow the community/randomizer convention so they can be matched
// against spoiler logs, other trackers and route notes.

const REGIONS = [
  {
    id: 'lw',
    name: 'Light World',
    short: 'LW',
    color: '#3f9e55',
    checks: [
      "Link's House",
      "Link's Uncle",
      'Secret Passage',
      "King's Tomb",
      'Kakariko Tavern',
      'Chicken House',
      "Aginah's Cave",
      "Sahasrahla's Hut - Left",
      "Sahasrahla's Hut - Middle",
      "Sahasrahla's Hut - Right",
      'Sahasrahla',
      'Kakariko Well - Top',
      'Kakariko Well - Left',
      'Kakariko Well - Middle',
      'Kakariko Well - Right',
      'Kakariko Well - Bottom',
      "Blind's Hideout - Top",
      "Blind's Hideout - Far Left",
      "Blind's Hideout - Left",
      "Blind's Hideout - Right",
      "Blind's Hideout - Far Right",
      'Bonk Rocks',
      'MMC - Far Left',
      'MMC - Left',
      'MMC - Right',
      'MMC - Far Right',
      'MMC - Guy',
      'Ice Rod Cave',
      'Bottle Merchant',
      'Magic Bat',
      'Sick Kid',
      'Hobo',
      'Bombos Tablet',
      'Ether Tablet',
      'King Zora',
      'Lost Woods Hideout',
      'Lumberjack Tree',
      'Cave 45',
      'Graveyard Ledge',
      'Checkerboard Cave',
      'Library',
      'Mushroom',
      'Potion Shop',
      'Maze Race',
      'Desert Ledge',
      'Lake Hylia Island',
      'Sunken Treasure',
      'Floodgate Chest',
      "Zora's Ledge",
      'Dig Spot',
      'Waterfall Fairy - Left',
      'Waterfall Fairy - Right',
      'Blacksmith',
      'Purple Chest',

      // Death Mountain is light world territory, so its checks live here too.
      'Old Man',
      'Spectacle Rock Cave',
      'Spectacle Rock',
      'Spiral Cave',
      'Mimic Cave',
      'Paradox Lower - Far Left',
      'Paradox Lower - Left',
      'Paradox Lower - Middle',
      'Paradox Lower - Right',
      'Paradox Lower - Far Right',
      'Paradox Upper - Left',
      'Paradox Upper - Right',
      'Floating Island',

      'Master Sword Pedestal',
    ],
  },
  {
    id: 'dw',
    name: 'Dark World',
    short: 'DW',
    color: '#8f4fb5',
    checks: [
      'Bumper Cave Ledge',
      'Catfish',
      'Pyramid',
      'Pyramid Fairy - Left',
      'Pyramid Fairy - Right',
      'Brewery',
      'C-Shaped House',
      'Chest Game',
      'Hammer Pegs',
      'Stumpy',
      'Digging Game',
      'Hype Cave - Top',
      'Hype Cave - Left',
      'Hype Cave - Right',
      'Hype Cave - Bottom',
      'Hype Cave - Guy',
      'Mire Shed - Left',
      'Mire Shed - Right',
      'Super Bunny Cave - Top',
      'Super Bunny Cave - Bottom',
      'Spike Cave',
      'Hookshot Cave - Bottom Right',
      'Hookshot Cave - Bottom Left',
      'Hookshot Cave - Top Left',
      'Hookshot Cave - Top Right',
    ],
  },
  {
    id: 'hc',
    name: 'Hyrule Castle',
    short: 'HC',
    color: '#5f86bf',
    checks: [
      'Map Chest',
      'Boomerang Chest',
      "Zelda's Cell",
      'Sewers - Dark Cross',
      'Sewers - Secret Room Left',
      'Sewers - Secret Room Middle',
      'Sewers - Secret Room Right',
      'Sanctuary',
    ],
  },
  {
    id: 'ep',
    name: 'Eastern Palace',
    short: 'EP',
    color: '#2fa877',
    checks: [
      'Cannonball Chest',
      'Map Chest',
      'Compass Chest',
      'Big Chest',
      'Big Key Chest',
      'Armos Knights',
    ],
  },
  {
    id: 'dp',
    name: 'Desert Palace',
    short: 'DP',
    color: '#d1a72b',
    checks: [
      'Map Chest',
      'Torch',
      'Compass Chest',
      'Big Key Chest',
      'Big Chest',
      'Lanmolas',
    ],
  },
  {
    id: 'toh',
    name: 'Tower of Hera',
    short: 'ToH',
    color: '#d97e42',
    checks: [
      'Basement Cage',
      'Map Chest',
      'Big Key Chest',
      'Compass Chest',
      'Big Chest',
      'Moldorm',
    ],
  },
  {
    id: 'ct',
    name: 'Castle Tower',
    short: 'CT',
    color: '#9295a3',
    checks: ['Room 03', 'Dark Maze'],
  },
  {
    id: 'pod',
    name: 'Palace of Darkness',
    short: 'PoD',
    color: '#5257a0',
    checks: [
      'Shooter Room',
      'Big Key Chest',
      'Stalfos Basement',
      'The Arena - Ledge',
      'The Arena - Bridge',
      'Map Chest',
      'Compass Chest',
      'Dark Basement - Left',
      'Dark Basement - Right',
      'Dark Maze - Top',
      'Dark Maze - Bottom',
      'Big Chest',
      'Harmless Hellway',
      'Helmasaur King',
    ],
  },
  {
    id: 'sp',
    name: 'Swamp Palace',
    short: 'SP',
    color: '#2f9aa8',
    checks: [
      'Entrance',
      'Map Chest',
      'Big Chest',
      'Compass Chest',
      'West Chest',
      'Big Key Chest',
      'Flooded Room - Left',
      'Flooded Room - Right',
      'Waterfall Room',
      'Arrghus',
    ],
  },
  {
    id: 'sw',
    name: 'Skull Woods',
    short: 'SW',
    color: '#74854f',
    checks: [
      'Big Chest',
      'Big Key Chest',
      'Compass Chest',
      'Map Chest',
      'Bridge Room',
      'Pot Prison',
      'Pinball Room',
      'Mothula',
    ],
  },
  {
    id: 'tt',
    name: "Thieves' Town",
    short: 'TT',
    color: '#a86333',
    checks: [
      'Map Chest',
      'Ambush Chest',
      'Compass Chest',
      'Big Key Chest',
      'Attic',
      "Blind's Cell",
      'Big Chest',
      'Blind',
    ],
  },
  {
    id: 'ip',
    name: 'Ice Palace',
    short: 'IP',
    color: '#4fb3d4',
    checks: [
      'Compass Chest',
      'Spike Room',
      'Map Chest',
      'Big Key Chest',
      'Iced T Room',
      'Freezor Chest',
      'Big Chest',
      'Kholdstare',
    ],
  },
  {
    id: 'mm',
    name: 'Misery Mire',
    short: 'MM',
    color: '#8272a8',
    checks: [
      'Bridge Chest',
      'Spike Chest',
      'Compass Chest',
      'Main Lobby',
      'Map Chest',
      'Big Key Chest',
      'Big Chest',
      'Vitreous',
    ],
  },
  {
    id: 'tr',
    name: 'Turtle Rock',
    short: 'TR',
    color: '#c04a41',
    checks: [
      'Roller Room - Left',
      'Roller Room - Right',
      'Compass Chest',
      'Chain Chomps',
      'Big Key Chest',
      'Big Chest',
      'Crystaroller Room',
      'Laser Bridge - Top Left',
      'Laser Bridge - Top Right',
      'Laser Bridge - Bottom Left',
      'Laser Bridge - Bottom Right',
      'Trinexx',
    ],
  },
  {
    id: 'gt',
    name: "Ganon's Tower",
    short: 'GT',
    color: '#ab4283',
    checks: [
      // Ordered to follow the tower's own layout.
      "Bob's Torch",
      'DMs Room - Top Left',
      'DMs Room - Top Right',
      'DMs Room - Bottom Left',
      'DMs Room - Bottom Right',
      'Map Chest',
      'Firesnake Room',
      'Randomizer Room - Top Left',
      'Randomizer Room - Top Right',
      'Randomizer Room - Bottom Left',
      'Randomizer Room - Bottom Right',
      'Big Chest',
      "Bob's Chest",
      'Big Key Chest',
      'Big Key Room - Left',
      'Big Key Room - Right',
      'Hope Room - Left',
      'Hope Room - Right',
      'Compass Room - Top Left',
      'Compass Room - Top Right',
      'Compass Room - Bottom Left',
      'Compass Room - Bottom Right',
      'Tile Room',
      'Mini Helmasaur Room - Left',
      'Mini Helmasaur Room - Right',
      'Pre-Moldorm Chest',
      'Moldorm Chest',
    ],
  },
];

function slug(text) {
  return text
    .toLowerCase()
    .replace(/'/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

// Flat list of every check, with a stable id of the form "<region>/<slug>".
// Dungeon check names repeat across dungeons ("Big Chest"), so the region
// prefix is what makes an id unique.
const CHECKS = REGIONS.flatMap((region) =>
  region.checks.map((name) => ({
    id: region.id + '/' + slug(name),
    name,
    region: region.id,
    regionName: region.name,
    regionShort: region.short,
    fullName: region.name + ' - ' + name,
  }))
);

const CHECKS_BY_ID = new Map(CHECKS.map((check) => [check.id, check]));

module.exports = { REGIONS, CHECKS, CHECKS_BY_ID };
