'use strict';

// Hand-drawn 12x12 pixel art, one grid per item. Each character indexes into
// PALETTE; '.' is transparent. The client turns a grid into an inline SVG of
// 1x1 rects, which scales crisply to any tile size.
//
// These are original approximations of the in-game items, not ripped sprites.

const PALETTE = {
  k: '#0d0d12', // outline
  w: '#f4f4f8', // white
  s: '#c6c8d4', // silver
  e: '#8b8fa0', // grey
  d: '#5a6078', // dark steel
  r: '#d83b32', // red
  R: '#8c1f1a', // dark red
  o: '#ef8a25', // orange
  y: '#f2cf3a', // gold
  g: '#4bb04b', // green
  G: '#24702c', // dark green
  b: '#3f63d4', // blue
  B: '#1e3080', // dark blue
  p: '#a94fd0', // purple
  n: '#9c6a2c', // brown
  N: '#5a3a14', // dark brown
  t: '#f5c48c', // skin
  c: '#57dcdc', // cyan
  m: '#f582bd', // pink
};

const ITEM_SPRITES = {
  sword: [
    '.....kk.....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '..kkkswkkk..',
    '..kyyyyyyk..',
    '..kkkNkkk...',
    '....kNk.....',
    '....kNk.....',
    '....kkk.....',
  ],
  shield: [
    '..kkkkkkkk..',
    '..kbbbbbbk..',
    '..kbwwwwbk..',
    '..kbwrrwbk..',
    '..kbwrrwbk..',
    '..kbwwwwbk..',
    '..kbbbbbbk..',
    '..kbbbbbbk..',
    '...kbbbbk...',
    '....kbbk....',
    '.....kk.....',
    '............',
  ],
  mail: [
    '.kk......kk.',
    '.kgkkkkkkgk.',
    '.kggggggggk.',
    '.kggggggggk.',
    '.kkggggggkk.',
    '..kggggggk..',
    '..kggggggk..',
    '..kggkkggk..',
    '..kgk..kgk..',
    '..kkk..kkk..',
    '............',
    '............',
  ],
  bow: [
    '..kk........',
    '.knnk.......',
    '.knnkk......',
    '.knn.kk.....',
    '.knn..kk....',
    '.knnsssssskk',
    '.knnsssssskk',
    '.knn..kk....',
    '.knn.kk.....',
    '.knnkk......',
    '.knnk.......',
    '..kk........',
  ],
  boomerang: [
    '....kkkk....',
    '...kbbbbk...',
    '..kbbwwbk...',
    '..kbbk.kk...',
    '..kbbk......',
    '..kbbk......',
    '..kbbk......',
    '..kbbbbkk...',
    '..kbbwwbbk..',
    '...kbbbbbk..',
    '....kkkkk...',
    '............',
  ],
  hookshot: [
    '............',
    '..kkk.......',
    '..ksk.......',
    '..kskkkkkk..',
    '..kskssssk..',
    '..kkkkkkkk..',
    '....kddddk..',
    '....kdyydk..',
    '....kddddk..',
    '....kkkkkk..',
    '............',
    '............',
  ],
  mushroom: [
    '............',
    '...kkkkkk...',
    '..krrrrrrk..',
    '.krwrrwrrrk.',
    '.krrrrrrrrk.',
    '.kkrrrrrrkk.',
    '...kkwwkk...',
    '....kwwk....',
    '....kwwk....',
    '....kwwk....',
    '....kkkk....',
    '............',
  ],
  powder: [
    '.....kk.....',
    '....kddk....',
    '...kkddkk...',
    '..kppppppk..',
    '.kpppwppppk.',
    '.kppppppppk.',
    '.kpwppppppk.',
    '.kppppppppk.',
    '.kpppppwppk.',
    '..kppppppk..',
    '...kkkkkk...',
    '............',
  ],
  firerod: [
    '.....rr.....',
    '....rkor....',
    '...rkookr...',
    '...rkoykr...',
    '....koyk....',
    '....kok.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....kkk.....',
    '............',
  ],
  icerod: [
    '.....cc.....',
    '....ckbc....',
    '...ckbbkc...',
    '...ckbwkc...',
    '....kbwk....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kkk.....',
    '............',
  ],
  bombos: [
    '....kkkk....',
    '..kkyyyykk..',
    '.kyyrrrryyk.',
    '.kyrrwwrryk.',
    'kyyrwrrwryyk',
    'kyyrwrrwryyk',
    '.kyrrwwrryk.',
    '.kyyrrrryyk.',
    '..kkyyyykk..',
    '....kkkk....',
    '............',
    '............',
  ],
  ether: [
    '....kkkk....',
    '..kkwwwwkk..',
    '.kwwbbbbwwk.',
    '.kwbbccbbwk.',
    'kwwbcwwcbwwk',
    'kwwbcwwcbwwk',
    '.kwbbccbbwk.',
    '.kwwbbbbwwk.',
    '..kkwwwwkk..',
    '....kkkk....',
    '............',
    '............',
  ],
  quake: [
    '....kkkk....',
    '..kkooookk..',
    '.koorrrrook.',
    '.korrRRrrok.',
    'koorRooRrook',
    'koorRooRrook',
    '.korrRRrrok.',
    '.koorrrrook.',
    '..kkooookk..',
    '....kkkk....',
    '............',
    '............',
  ],
  lamp: [
    '.....kk.....',
    '....keek....',
    '...keeeek...',
    '..kkkkkkkk..',
    '..kwyyyywk..',
    '..kyyyyyyk..',
    '..kyywwyyk..',
    '..kyyyyyyk..',
    '..kwyyyywk..',
    '..kkkkkkkk..',
    '...keeeek...',
    '....kkkk....',
  ],
  hammer: [
    '............',
    '.kkkkkkkk...',
    '.kssssssk...',
    'kseewweesk..',
    'kseewweesk..',
    '.kssssssk...',
    '.kkkkNkkk...',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kkk....',
  ],
  shovel: [
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '....kkNkk...',
    '....kNNNk...',
    '...kkNNNkk..',
    '...kssssk...',
    '..kssssssk..',
    '..kssssssk..',
    '..kkssssk...',
    '....kkkk....',
  ],
  flute: [
    '............',
    '............',
    '............',
    '..kkkkkkkk..',
    '.knnnnnnnnk.',
    'knNnkNnkNnnk',
    'knnnnnnnnnnk',
    '.knnnnnnnnk.',
    '..kkkkkkkk..',
    '............',
    '............',
    '............',
  ],
  bugnet: [
    '.........kk.',
    '........kwk.',
    '.......kwk..',
    '..kkk.kwk...',
    '.kwwwkwk....',
    'kwwwwwk.....',
    'kwwwwwk.....',
    '.kwwwkwk....',
    '..kkk.kwk...',
    '.......kwk..',
    '........kwk.',
    '.........kk.',
  ],
  book: [
    '............',
    '.kkkkkkkkkk.',
    '.kRyyykyyyk.',
    '.kRywykywyk.',
    '.kRyyykyyyk.',
    '.kRywykywyk.',
    '.kRyyykyyyk.',
    '.kRRRRkRRRk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
    '............',
  ],
  bottle: [
    '.....kk.....',
    '....krrk....',
    '....kwwk....',
    '....kwwk....',
    '...kkwwkk...',
    '..kwggggwk..',
    '..kwggggwk..',
    '..kggggggk..',
    '..kggggggk..',
    '..kggggggk..',
    '..kkkkkkkk..',
    '............',
  ],
  somaria: [
    '....kkkk....',
    '...krrrrk...',
    '..krrwwrrk..',
    '..krwwrrrk..',
    '...krrrrk...',
    '....kkkk....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....kkk.....',
  ],
  byrna: [
    '....kkkk....',
    '...kbbbbk...',
    '..kbbccbbk..',
    '..kbccbbbk..',
    '...kbbbbk...',
    '....kkkk....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kkk.....',
  ],
  cape: [
    '...kkkkkk...',
    '..kwrrrrwk..',
    '.krrrrrrrrk.',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    '.krrrrrrrrk.',
    '.kRRRRRRRRk.',
    '..kkkkkkkk..',
    '............',
  ],
  mirror: [
    '....kkkk....',
    '...kppppk...',
    '..kpccccpk..',
    '..kpcwccpk..',
    '..kpccccpk..',
    '...kppppk...',
    '....kkkk....',
    '....kpk.....',
    '....kpk.....',
    '...kpppk....',
    '...kkkkk....',
    '............',
  ],
  boots: [
    '............',
    '..kk........',
    '..kbk.......',
    '..kbk.......',
    '..kbbkkk....',
    '..kbbbbbk...',
    '..kbbbbbbk..',
    '.kkbbbbbbk..',
    '.kwwwwwwwwk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  flippers: [
    '............',
    '..kkk..kkk..',
    '..kck..kck..',
    '..kck..kck..',
    '.kkck..kckk.',
    '.kcck..kcck.',
    '.kcck..kcck.',
    '.kcck..kcck.',
    '.kkck..kckk.',
    '..kkk..kkk..',
    '............',
    '............',
  ],
  moonpearl: [
    '....kkkk....',
    '...kwwwwk...',
    '..kwwwwbbk..',
    '.kwwwwbbbbk.',
    '.kwwbbbbbbk.',
    '.kwbbbbbbBk.',
    '.kbbbbbbbBk.',
    '.kbbbbbbBBk.',
    '..kbbbbBBk..',
    '...kBBBBk...',
    '....kkkk....',
    '............',
  ],
  glove: [
    '............',
    '...kk.kk....',
    '..kwkkwkkk..',
    '..kwwwwwwk..',
    '.kkwwwwwwk..',
    '.kwwwwwwwk..',
    '.kwwwwwwwk..',
    '..kwwwwwwk..',
    '..kyyyyyyk..',
    '..kyyyyyyk..',
    '..kkkkkkkk..',
    '............',
  ],
  halfmagic: [
    '.....kk.....',
    '....kkkk....',
    '...kwwwwk...',
    '...kwppwk...',
    '..kwppppwk..',
    '..kppppppk..',
    '..kppppppk..',
    '..kppwpppk..',
    '..kppppppk..',
    '..kppppppk..',
    '..kkkkkkkk..',
    '............',
  ],
};

// Small glyphs used on the 216 check tiles. The glyph is picked from the
// check's name (see kindForCheck) so a tile reads as "chest", "boss drop",
// "NPC" and so on at a glance.
const ICON_SPRITES = {
  chest: [
    '............',
    '..kkkkkkkk..',
    '.knnnnnnnnk.',
    '.knnnnnnnnk.',
    '.kkkkkkkkkk.',
    '.knnnnnnnnk.',
    '.knnnkyknnk.',
    '.knnnkyknnk.',
    '.knnnnnnnnk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  bigchest: [
    '............',
    '..kkkkkkkk..',
    '.kyyyyyyyyk.',
    '.kyooooooyk.',
    '.kkkkkkkkkk.',
    '.kyooooooyk.',
    '.kyyykwkyyk.',
    '.kyyykwkyyk.',
    '.kyooooooyk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  npc: [
    '............',
    '....kkkk....',
    '...kttttk...',
    '...ktktkk...',
    '...kttttk...',
    '....kttk....',
    '..kkkkkkkk..',
    '.kbbbbbbbbk.',
    '.kbbbbbbbbk.',
    '.kbbbbbbbbk.',
    '.kkkkkkkkkk.',
    '............',
  ],
  boss: [
    '............',
    '..kk....kk..',
    '.krrkkkkrrk.',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    '.krrrrrrrrk.',
    '..krrrrrrk..',
    '...krrrrk...',
    '....krrk....',
    '.....kk.....',
    '............',
  ],
  tablet: [
    '............',
    '..kkkkkkkk..',
    '.keeeeeeeek.',
    '.kewwwwwwek.',
    '.kewkkkkwek.',
    '.kewkwwkwek.',
    '.kewkkkkwek.',
    '.kewwwwwwek.',
    '.keeeeeeeek.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  sparkle: [
    '............',
    '.....kk.....',
    '....kyyk....',
    '.kk.kyyk.kk.',
    '.kykkyykkyk.',
    '..kyyyyyyk..',
    '..kyyyyyyk..',
    '.kykkyykkyk.',
    '.kk.kyyk.kk.',
    '....kyyk....',
    '.....kk.....',
    '............',
  ],
};

const BOSSES = [
  'Armos Knights',
  'Lanmolas',
  'Moldorm',
  'Helmasaur King',
  'Arrghus',
  'Mothula',
  'Blind',
  'Kholdstare',
  'Vitreous',
  'Trinexx',
];

const NPCS = [
  'Bottle Merchant',
  'Sahasrahla',
  'Sick Kid',
  'Hobo',
  'King Zora',
  'Blacksmith',
  'Stumpy',
  'Catfish',
  'Library',
  'Mushroom',
  'Potion Shop',
  'Old Man',
  'Magic Bat',
  'Purple Chest',
  "Link's Uncle",
  'Chest Game',
  'Digging Game',
  'Maze Race',
  'Hammer Pegs',
  'Mushroom',
];

const TABLETS = ['Bombos Tablet', 'Ether Tablet', 'Master Sword Pedestal'];

const FREESTANDING = [
  "Zora's Ledge",
  'Desert Ledge',
  'Lake Hylia Island',
  'Sunken Treasure',
  'Floating Island',
  'Spectacle Rock',
  'Pyramid',
  'Bumper Cave Ledge',
  'Graveyard Ledge',
  'Lumberjack Tree',
  'Pegasus Rocks',
  'Flute Spot',
  'Sanctuary',
  'Secret Passage',
  "Bob's Torch",
  'Torch',
  'Basement Cage',
  "Zelda's Cell",
  'Spectacle Rock Cave',
  'Mimic Cave',
  'Ice Rod Cave',
  'Checkerboard Cave',
  'Cave 45',
  'Lost Woods Hideout',
];

// Which glyph a check tile gets.
function kindForCheck(check) {
  const name = check.name;
  if (BOSSES.includes(name)) return 'boss';
  if (TABLETS.includes(name)) return 'tablet';
  if (NPCS.includes(name) || /Generous Guy/.test(name)) return 'npc';
  if (FREESTANDING.includes(name)) return 'sparkle';
  if (/^Big Chest$/.test(name)) return 'bigchest';
  return 'chest';
}

module.exports = { PALETTE, ITEM_SPRITES, ICON_SPRITES, kindForCheck };
