'use strict';

// Hand-drawn 12x12 pixel art, one grid per item. Each character indexes into
// PALETTE; '.' is transparent. The client turns a grid into an inline SVG of
// 1x1 rects, which scales crisply to any tile size.
//
// These are original approximations of the in-game items, not ripped sprites.

const PALETTE = {
  k: '#0d0d12', // outline
  w: '#f4f4f8', // white
  s: '#c6c8d4', // silver
  e: '#8b8fa0', // grey
  d: '#5a6078', // dark steel
  r: '#d83b32', // red
  R: '#8c1f1a', // dark red
  o: '#ef8a25', // orange
  y: '#f2cf3a', // gold
  g: '#4bb04b', // green
  G: '#24702c', // dark green
  b: '#3f63d4', // blue
  B: '#1e3080', // dark blue
  p: '#a94fd0', // purple
  n: '#9c6a2c', // brown
  N: '#5a3a14', // dark brown
  t: '#f5c48c', // skin
  c: '#57dcdc', // cyan
  m: '#f582bd', // pink
};

const ITEM_SPRITES = {
  sword: [
    '.....kk.....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '....kswk....',
    '..kkkswkkk..',
    '..kyyyyyyk..',
    '..kkkNkkk...',
    '....kNk.....',
    '....kNk.....',
    '....kkk.....',
  ],
  shield: [
    '..kkkkkkkk..',
    '..kbbbbbbk..',
    '..kbwwwwbk..',
    '..kbwrrwbk..',
    '..kbwrrwbk..',
    '..kbwwwwbk..',
    '..kbbbbbbk..',
    '..kbbbbbbk..',
    '...kbbbbk...',
    '....kbbk....',
    '.....kk.....',
    '............',
  ],
  mail: [
    '.kk......kk.',
    '.kgkkkkkkgk.',
    '.kggggggggk.',
    '.kggggggggk.',
    '.kkggggggkk.',
    '..kggggggk..',
    '..kggggggk..',
    '..kggkkggk..',
    '..kgk..kgk..',
    '..kkk..kkk..',
    '............',
    '............',
  ],
  bow: [
    '..kk........',
    '.knnk.......',
    '.knnkk......',
    '.knn.kk.....',
    '.knn..kk....',
    '.knnsssssskk',
    '.knnsssssskk',
    '.knn..kk....',
    '.knn.kk.....',
    '.knnkk......',
    '.knnk.......',
    '..kk........',
  ],
  blueboomerang: [
    '....kkkk....',
    '...kbbbbk...',
    '..kbbwwbk...',
    '..kbbk.kk...',
    '..kbbk......',
    '..kbbk......',
    '..kbbk......',
    '..kbbbbkk...',
    '..kbbwwbbk..',
    '...kbbbbbk..',
    '....kkkkk...',
    '............',
  ],
  redboomerang: [
    '....kkkk....',
    '...krrrrk...',
    '..krrwwrk...',
    '..krrk.kk...',
    '..krrk......',
    '..krrk......',
    '..krrk......',
    '..krrrrkk...',
    '..krrwwrrk..',
    '...krrrrrk..',
    '....kkkkk...',
    '............',
  ],
  hookshot: [
    '............',
    '..kkk.......',
    '..ksk.......',
    '..kskkkkkk..',
    '..kskssssk..',
    '..kkkkkkkk..',
    '....kddddk..',
    '....kdyydk..',
    '....kddddk..',
    '....kkkkkk..',
    '............',
    '............',
  ],
  mushroom: [
    '............',
    '...kkkkkk...',
    '..krrrrrrk..',
    '.krwrrwrrrk.',
    '.krrrrrrrrk.',
    '.kkrrrrrrkk.',
    '...kkwwkk...',
    '....kwwk....',
    '....kwwk....',
    '....kwwk....',
    '....kkkk....',
    '............',
  ],
  powder: [
    '.....kk.....',
    '....kddk....',
    '...kkddkk...',
    '..kppppppk..',
    '.kpppwppppk.',
    '.kppppppppk.',
    '.kpwppppppk.',
    '.kppppppppk.',
    '.kpppppwppk.',
    '..kppppppk..',
    '...kkkkkk...',
    '............',
  ],
  firerod: [
    '.....rr.....',
    '....rkor....',
    '...rkookr...',
    '...rkoykr...',
    '....koyk....',
    '....kok.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....kkk.....',
    '............',
  ],
  icerod: [
    '.....cc.....',
    '....ckbc....',
    '...ckbbkc...',
    '...ckbwkc...',
    '....kbwk....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kkk.....',
    '............',
  ],
  bombos: [
    '....kkkk....',
    '..kkyyyykk..',
    '.kyyrrrryyk.',
    '.kyrrwwrryk.',
    'kyyrwrrwryyk',
    'kyyrwrrwryyk',
    '.kyrrwwrryk.',
    '.kyyrrrryyk.',
    '..kkyyyykk..',
    '....kkkk....',
    '............',
    '............',
  ],
  ether: [
    '....kkkk....',
    '..kkwwwwkk..',
    '.kwwbbbbwwk.',
    '.kwbbccbbwk.',
    'kwwbcwwcbwwk',
    'kwwbcwwcbwwk',
    '.kwbbccbbwk.',
    '.kwwbbbbwwk.',
    '..kkwwwwkk..',
    '....kkkk....',
    '............',
    '............',
  ],
  quake: [
    '....kkkk....',
    '..kkooookk..',
    '.koorrrrook.',
    '.korrRRrrok.',
    'koorRooRrook',
    'koorRooRrook',
    '.korrRRrrok.',
    '.koorrrrook.',
    '..kkooookk..',
    '....kkkk....',
    '............',
    '............',
  ],
  lamp: [
    '.....kk.....',
    '....keek....',
    '...keeeek...',
    '..kkkkkkkk..',
    '..kwyyyywk..',
    '..kyyyyyyk..',
    '..kyywwyyk..',
    '..kyyyyyyk..',
    '..kwyyyywk..',
    '..kkkkkkkk..',
    '...keeeek...',
    '....kkkk....',
  ],
  hammer: [
    '............',
    '.kkkkkkkk...',
    '.kssssssk...',
    'kseewweesk..',
    'kseewweesk..',
    '.kssssssk...',
    '.kkkkNkkk...',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kkk....',
  ],
  shovel: [
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '.....kNk....',
    '....kkNkk...',
    '....kNNNk...',
    '...kkNNNkk..',
    '...kssssk...',
    '..kssssssk..',
    '..kssssssk..',
    '..kkssssk...',
    '....kkkk....',
  ],
  flute: [
    '............',
    '............',
    '............',
    '..kkkkkkkk..',
    '.knnnnnnnnk.',
    'knNnkNnkNnnk',
    'knnnnnnnnnnk',
    '.knnnnnnnnk.',
    '..kkkkkkkk..',
    '............',
    '............',
    '............',
  ],
  bugnet: [
    '.........kk.',
    '........kwk.',
    '.......kwk..',
    '..kkk.kwk...',
    '.kwwwkwk....',
    'kwwwwwk.....',
    'kwwwwwk.....',
    '.kwwwkwk....',
    '..kkk.kwk...',
    '.......kwk..',
    '........kwk.',
    '.........kk.',
  ],
  book: [
    '............',
    '.kkkkkkkkkk.',
    '.kRyyykyyyk.',
    '.kRywykywyk.',
    '.kRyyykyyyk.',
    '.kRywykywyk.',
    '.kRyyykyyyk.',
    '.kRRRRkRRRk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
    '............',
  ],
  bottle: [
    '.....kk.....',
    '....krrk....',
    '....kwwk....',
    '....kwwk....',
    '...kkwwkk...',
    '..kwggggwk..',
    '..kwggggwk..',
    '..kggggggk..',
    '..kggggggk..',
    '..kggggggk..',
    '..kkkkkkkk..',
    '............',
  ],
  somaria: [
    '....kkkk....',
    '...krrrrk...',
    '..krrwwrrk..',
    '..krwwrrrk..',
    '...krrrrk...',
    '....kkkk....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....krk.....',
    '....kkk.....',
  ],
  byrna: [
    '....kkkk....',
    '...kbbbbk...',
    '..kbbccbbk..',
    '..kbccbbbk..',
    '...kbbbbk...',
    '....kkkk....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kbk.....',
    '....kkk.....',
  ],
  cape: [
    '...kkkkkk...',
    '..kwrrrrwk..',
    '.krrrrrrrrk.',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    'krrrrrrrrrrk',
    '.krrrrrrrrk.',
    '.kRRRRRRRRk.',
    '..kkkkkkkk..',
    '............',
  ],
  mirror: [
    '....kkkk....',
    '...kppppk...',
    '..kpccccpk..',
    '..kpcwccpk..',
    '..kpccccpk..',
    '...kppppk...',
    '....kkkk....',
    '....kpk.....',
    '....kpk.....',
    '...kpppk....',
    '...kkkkk....',
    '............',
  ],
  boots: [
    '............',
    '..kk........',
    '..kbk.......',
    '..kbk.......',
    '..kbbkkk....',
    '..kbbbbbk...',
    '..kbbbbbbk..',
    '.kkbbbbbbk..',
    '.kwwwwwwwwk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  flippers: [
    '............',
    '..kkk..kkk..',
    '..kck..kck..',
    '..kck..kck..',
    '.kkck..kckk.',
    '.kcck..kcck.',
    '.kcck..kcck.',
    '.kcck..kcck.',
    '.kkck..kckk.',
    '..kkk..kkk..',
    '............',
    '............',
  ],
  moonpearl: [
    '....kkkk....',
    '...kwwwwk...',
    '..kwwwwbbk..',
    '.kwwwwbbbbk.',
    '.kwwbbbbbbk.',
    '.kwbbbbbbBk.',
    '.kbbbbbbbBk.',
    '.kbbbbbbBBk.',
    '..kbbbbBBk..',
    '...kBBBBk...',
    '....kkkk....',
    '............',
  ],
  glove: [
    '............',
    '...kk.kk....',
    '..kwkkwkkk..',
    '..kwwwwwwk..',
    '.kkwwwwwwk..',
    '.kwwwwwwwk..',
    '.kwwwwwwwk..',
    '..kwwwwwwk..',
    '..kyyyyyyk..',
    '..kyyyyyyk..',
    '..kkkkkkkk..',
    '............',
  ],
  bigkey: [
    '....kkkk....',
    '...kyyyyk...',
    '..kyykkyyk..',
    '..kyk..kyk..',
    '..kyk..kyk..',
    '..kyykkyyk..',
    '...kyyyyk...',
    '....kyyk....',
    '....kyykkk..',
    '....kyyk....',
    '....kyykk...',
    '....kkkk....',
  ],
  smallkey: [
    '............',
    '....kkk.....',
    '...ksssk....',
    '...ksksk....',
    '...ksssk....',
    '....ksk.....',
    '....ksk.....',
    '....kskk....',
    '....ksk.....',
    '....kskk....',
    '....kkk.....',
    '............',
  ],
  halfmagic: [
    '.....kk.....',
    '....kkkk....',
    '...kwwwwk...',
    '...kwppwk...',
    '..kwppppwk..',
    '..kppppppk..',
    '..kppppppk..',
    '..kppwpppk..',
    '..kppppppk..',
    '..kppppppk..',
    '..kkkkkkkk..',
    '............',
  ],
};

// Small glyphs used on the 216 check tiles. The glyph is picked from the
// check's name (see kindForCheck) so a tile reads as "chest", "boss drop",
// "NPC" and so on at a glance.
const ICON_SPRITES = {
  chest: [
    '............',
    '..kkkkkkkk..',
    '.knnnnnnnnk.',
    '.knnnnnnnnk.',
    '.kkkkkkkkkk.',
    '.knnnnnnnnk.',
    '.knnnkyknnk.',
    '.knnnkyknnk.',
    '.knnnnnnnnk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  bigchest: [
    '............',
    '..kkkkkkkk..',
    '.kyyyyyyyyk.',
    '.kyooooooyk.',
    '.kkkkkkkkkk.',
    '.kyooooooyk.',
    '.kyyykwkyyk.',
    '.kyyykwkyyk.',
    '.kyooooooyk.',
    '.kkkkkkkkkk.',
    '............',
    '............',
  ],
  npc: [
    '............',
    '....kkkk....',
    '...kttttk...',
    '...ktktkk...',
    '...kttttk...',
    '....kttk....',
    '..kkkkkkkk..',
    '.kbbbbbbbbk.',
    '.kbbbbbbbbk.',
    '.kbbbbbbbbk.',
    '.kkkkkkkkkk.',
    '............',
  ],
  boss: [
    '...kkkkkk...',
    '..kwwwwwwk..',
    '.kwwwwwwwwk.',
    '.kwkkwwkkwk.',
    '.kwkkwwkkwk.',
    '.kwwwwwwwwk.',
    '.kwwwkkwwwk.',
    '.kwwwwwwwwk.',
    '..kwwwwwwk..',
    '..kwwwwwwk..',
    '..kwkwkwwk..',
    '..kkkkkkkk..',
  ],
  // Item art doubling as check glyphs — see CHECK_ICONS. These are the drawn
  // fallbacks; a PNG in public/sprites/checks wins when one is present.
  mirror: ITEM_SPRITES.mirror,
  cape: ITEM_SPRITES.cape,
  book: ITEM_SPRITES.book,
  sword: ITEM_SPRITES.sword,
  hammer: ITEM_SPRITES.hammer,
  boots: ITEM_SPRITES.boots,
  bottle: ITEM_SPRITES.bottle,
  flippers: ITEM_SPRITES.flippers,
  hookshot: ITEM_SPRITES.hookshot,
  powder: ITEM_SPRITES.powder,
  glove: ITEM_SPRITES.glove,
  shovel: ITEM_SPRITES.shovel,
  icerod: ITEM_SPRITES.icerod,
  mushroom: ITEM_SPRITES.mushroom,
  sparkle: [
    '............',
    '.....kk.....',
    '....kyyk....',
    '.kk.kyyk.kk.',
    '.kykkyykkyk.',
    '..kyyyyyyk..',
    '..kyyyyyyk..',
    '.kykkyykkyk.',
    '.kk.kyyk.kk.',
    '....kyyk....',
    '.....kk.....',
    '............',
  ],
};

const BOSSES = [
  'Armos Knights',
  'Lanmolas',
  'Moldorm',
  'Helmasaur King',
  'Arrghus',
  'Mothula',
  'Blind',
  'Kholdstare',
  'Vitreous',
  'Trinexx',
];

const NPCS = [
  'Bottle Merchant',
  'King Zora',
  'Potion Shop',
  "Link's Uncle",
  'Maze Race',
];

/**
 * Checks that show a specific item rather than a generic glyph — usually the
 * thing that gets you in (mirror, cape, flippers, hammer) or the thing you
 * read or find there (book, sword). Beats every rule below it.
 */
const CHECK_ICONS = new Map([
  ['Bombos Tablet', 'book'],
  ['Ether Tablet', 'book'],
  ['Master Sword Pedestal', 'sword'],
  ['Hammer Pegs', 'hammer'],
  ['Chest Game', 'chest'],
  ['Bonk Rocks', 'boots'],
  ['Cave 45', 'mirror'],
  ['Checkerboard Cave', 'mirror'],
  ['Graveyard Ledge', 'mirror'],
  ['Bumper Cave Ledge', 'cape'],
  ['Sick Kid', 'bottle'],
  ['Hobo', 'flippers'],
  ["Zora's Ledge", 'flippers'],
  ['Waterfall Fairy - Left', 'flippers'],
  ['Waterfall Fairy - Right', 'flippers'],
  ['Magic Bat', 'powder'],
  ['Blacksmith', 'glove'],
  ['Floating Island', 'mirror'],
  ['Purple Chest', 'purplechest'],
  ['Digging Game', 'shovel'],
  ['Ice Rod Cave', 'icerod'],
  ['Library', 'boots'],
  ['Mushroom', 'mushroom'],
  ['Lumberjack Tree', 'boots'],
  ["Aginah's Cave", 'bomb'],
  ['Catfish', 'catfish'],
  ["Link's House", 'link'],
  ['Stumpy', 'stumpy'],
  ['Chicken House', 'chicken'],
  ['Pyramid Fairy - Left', 'superbomb'],
  ['Pyramid Fairy - Right', 'superbomb'],
  ['Mimic Cave', 'mirror'],
  ['Spectacle Rock', 'mirror'],
  ["King's Tomb", 'boots'],
  ['Lake Hylia Island', 'mirror'],
  ['Super Bunny Cave - Top', 'bunny'],
  ['Super Bunny Cave - Bottom', 'bunny'],
  ['Spike Cave', 'spike'],
  ['Old Man', 'oldman'],
  ['Sahasrahla', 'greenpendant'],
  ['Mire Shed - Left', 'mireshed'],
  ['Mire Shed - Right', 'mireshed'],
  ['Pyramid', 'pyramid'],
]);

const FREESTANDING = [
  'Desert Ledge',
  'Sunken Treasure',
  'Flute Spot',
  'Sanctuary',
  'Secret Passage',
  "Bob's Torch",
  'Torch',
  "Zelda's Cell",
  'Checkerboard Cave',
  'Cave 45',
  'Lost Woods Hideout',
];

// Which glyph a check tile gets.
function kindForCheck(check) {
  const name = check.name;
  if (CHECK_ICONS.has(name)) return CHECK_ICONS.get(name);
  // The whole cave is gated behind the hookshot, so every chest in it says so.
  if (name.startsWith('Hookshot Cave')) return 'hookshot';
  // Ahead of the "- Guy" rule below, so the generous guy in each matches too.
  if (name.startsWith('MMC')) return 'mmc';
  if (name.startsWith('Hype Cave')) return 'bomb';
  if (BOSSES.includes(name)) return 'boss';
  // "MMC - Guy" / "Hype Cave - Guy" are the generous-guy chest rooms.
  if (NPCS.includes(name) || /- Guy$/.test(name)) return 'npc';
  if (FREESTANDING.includes(name)) return 'sparkle';
  if (/^Big Chest$/.test(name)) return 'bigchest';
  return 'chest';
}

// No drawn art for these two, so an ordinary chest stands in when their
// images are missing.
ICON_SPRITES.mmc = ICON_SPRITES.chest;
ICON_SPRITES.purplechest = ICON_SPRITES.chest;

// Likewise for the character and super-bomb glyphs: no drawn art, so the
// nearest generic one stands in until the image is there.
ICON_SPRITES.catfish = ICON_SPRITES.npc;
ICON_SPRITES.stumpy = ICON_SPRITES.npc;
ICON_SPRITES.chicken = ICON_SPRITES.npc;
ICON_SPRITES.link = ICON_SPRITES.npc;
ICON_SPRITES.bunny = ICON_SPRITES.npc;
ICON_SPRITES.spike = ICON_SPRITES.chest;
ICON_SPRITES.oldman = ICON_SPRITES.npc;
ICON_SPRITES.greenpendant = ICON_SPRITES.sparkle;
ICON_SPRITES.mireshed = ICON_SPRITES.chest;
ICON_SPRITES.pyramid = ICON_SPRITES.sparkle;

// The bomb-in checks. Drawn fallback only; the real image wins when present.
ICON_SPRITES.bomb = [
  '.......kkk..',
  '......kyyk..',
  '.....kyk....',
  '.....kk.....',
  '..kkkkkk....',
  '.kkddddkk...',
  'kkdwddddkk..',
  'kkddddddkk..',
  'kkddddddkk..',
  '.kkddddkk...',
  '..kkkkkk....',
  '............',
];

// Defined last because it borrows the bomb above.
ICON_SPRITES.superbomb = ICON_SPRITES.bomb;

module.exports = { PALETTE, ITEM_SPRITES, ICON_SPRITES, kindForCheck };
